angular.module("myApp")
    .controller("proCon", proCon)
    .controller("indexCon", indexCon)
    .controller("cineHotCon", cineHotCon)
    .controller("cinemaCon",cinemaCon )
    .controller("foreign", foreign)
    .controller("cityCon", cityCon)
    .controller("searchCon", searchCon)
    .controller("settingCon", settingCon)
    .controller("theateCon",theateCon)
    .controller("contentCon",contentCon)
    .controller("moreCon",moreCon)
    .controller("miniCon",miniCon )
    .controller("loginCon",loginCon )
    .controller("person",person )
    .controller("registerCon",registerCon )
    .controller("settingCon", settingCon)
    .controller("detectorCon",detectorCon)
